create table if not exists public.inference_logs (
    id bigint generated by default as identity primary key,
    log_id varchar(255) not null unique,
    conversation_id varchar(255) not null,
    session_id varchar(255) not null,
    timestamp timestamptz not null,
    latency_ms double precision not null,
    model varchar(255) not null,
    provider varchar(255) not null,
    input_tokens integer not null,
    output_tokens integer not null,
    total_tokens integer not null,
    request_preview text not null,
    response_preview text not null,
    status varchar(64) not null,
    error_message text,
    temperature double precision not null,
    max_tokens integer not null,
    user_id varchar(255),
    custom_metadata jsonb,
    extracted_metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint inference_logs_latency_ms_non_negative check (latency_ms >= 0),
    constraint inference_logs_input_tokens_non_negative check (input_tokens >= 0),
    constraint inference_logs_output_tokens_non_negative check (output_tokens >= 0),
    constraint inference_logs_total_tokens_non_negative check (total_tokens >= 0),
    constraint inference_logs_token_total_matches check (total_tokens = input_tokens + output_tokens),
    constraint inference_logs_temperature_non_negative check (temperature >= 0),
    constraint inference_logs_max_tokens_positive check (max_tokens > 0),
    constraint inference_logs_status_allowed check (lower(status) in ('success', 'error', 'failed', 'timeout'))
);

create index if not exists ix_inference_logs_conversation_id
    on public.inference_logs (conversation_id);

create index if not exists ix_inference_logs_session_id
    on public.inference_logs (session_id);

create index if not exists ix_inference_logs_timestamp
    on public.inference_logs (timestamp);

create index if not exists ix_inference_logs_status
    on public.inference_logs (status);

create index if not exists ix_inference_logs_user_id
    on public.inference_logs (user_id);

create index if not exists ix_inference_logs_custom_metadata
    on public.inference_logs using gin (custom_metadata);

create index if not exists ix_inference_logs_extracted_metadata
    on public.inference_logs using gin (extracted_metadata);

alter table public.inference_logs enable row level security;

create policy "service role can manage inference logs"
    on public.inference_logs
    for all
    to service_role
    using (true)
    with check (true);
